from .Armadillo import Armadillo
from .Bat import Bat
from .Bear import Bear
from .Buffalo import Buffalo
from .Camel import Camel
from .Chameleon import Chameleon
from .Cheetah import Cheetah
from .Coyote import Coyote
from .Crocodile import Crocodile
from .Dog import Dog
from .Eagle import Eagle
from .Elephant import Elephant
from .Flamingo import Flamingo
from .Gazelle import Gazelle
from .Giraffe import Giraffe
from .Hippo import Hippo
from .Kangaroo import Kangaroo
from .Lion import Lion
from .Llama import Llama
from .Monkey import Monkey
from .Okapi import Okapi
from .Ostrich import Ostrich
from .Panda import Panda
from .Parrot import Parrot
from .Peacock import Peacock
from .Penguin import Penguin
from .Porcupine import Porcupine
from .Rhino import Rhino
from .Seal import Seal
from .Skunk import Skunk
from .Sloth import Sloth
from .Snake import Snake
from .TasmanianDevil import TasmanianDevil
from .Tiger import Tiger
from .Vulture import Vulture
from .Weasel import Weasel
from .Zebra import Zebra
